services:
  my_read_memo_web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: |
      bash -c "
        rm -f tmp/pids/server.pid && 
        bundle exec rails assets:precompile && 
        bundle exec rails s -p 3000 -b '0.0.0.0' -e production
      "
    # 上記のdbイメージで指定したユーザー名とパスワードをrails側でも指定するため環境変数に設定。
    environment:
      RDS_DB_USER: ${RDS_DB_USER}
      RDS_DB_PASSWORD: ${RDS_DB_PASSWORD}
      RDS_DB_HOST: ${RDS_DB_HOST}
      RDS_DB_NAME: ${RDS_DB_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 'true'

  my_read_memo_webserver:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./docker/nginx/conf/prod/:/etc/nginx/conf.d/
      - /etc/letsencrypt/live/yondeco.site:/etc/letsencrypt/live/yondeco.site
      - /etc/letsencrypt/archive/yondeco.site:/etc/letsencrypt/archive/yondeco.site
    # my_read_memo_webserver が my_read_memo_web に依存するように設定
    # Railsアプリケーションが完全に起動してからNginxが起動
    depends_on:
      - my_read_memo_web
