services:
  my_read_memo_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  my_read_memo_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && bin/vite dev"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/myapp
    tty: true # 疑似ターミナル (pseudo-TTY) を割り当て。https://docs.docker.jp/compose/compose-file/index.html#tty
    stdin_open: true # サービス コンテナに標準入力を割り当てて実行するよう設定(https://docs.docker.jp/compose/compose-file/index.html#stdin-open)。
    depends_on:
      - my_read_memo_db

  my_read_memo_webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./docker/nginx/conf/dev/:/etc/nginx/conf.d/
      - /etc/letsencrypt/live/localhost.yondeco.site:/etc/letsencrypt/live/localhost.yondeco.site
      - /etc/letsencrypt/archive/localhost.yondeco.site:/etc/letsencrypt/archive/localhost.yondeco.site

    # my_read_memo_webserver が my_read_memo_web に依存するように設定
    # Railsアプリケーションが完全に起動してからNginxが起動
    depends_on:
      - my_read_memo_web

volumes:
  postgres_volume:
