default: &default
  adapter: postgresql
  encoding: unicode
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  #host: localhost
  host: my_read_memo_db

development:
  <<: *default
  database: my_read_memo_development

test:
  <<: *default
  database: my_read_memo_test

production:
  <<: *default
  database: my_read_memo_production
  username: <%= ENV['DOCKER_DB_USER'] %>
  password: <%= ENV['DOCKER_DB_PASSWORD'] %>
  #host: <%= ENV['MY_READ_MEMO_DATABASE_HOST'] %>
